# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: linhdb
google_analytics: linhdb
title: linhdb

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: linhdb

description: Stylish Jekyll Theme
author:
  name: Linh Dao
  email: baolinhtb@gmail.com
  github: baolinhtb
  twitter: linhdb88
  pinterest: linhdb
  linkedin: baolinhtb
  bio: B
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
